/*
  * Generated by cppsrc.sh
  * On 2015-10-21 18:11:28,94
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

//#include "Camera.h"
#include <pch.h>

namespace MoonGlare {
namespace Renderer {


} //namespace Renderer 
} //namespace MoonGlare 
