/*
  * Generated by cppsrc.sh
  * On 2015-11-12 17:12:25,48
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include <pch.h>
#include "GraphicTypes.h"
#include "Generic/nfGeneric.h"
#include "Device/nDevice.h"
#include "Frame.h"

namespace MoonGlare {
namespace Renderer {

Frame::Frame(): m_PreCommands(RendererStaticSettings::Limits::FramePreCommands) {

#ifdef DEBUG_MEMORY
	m_PreCommands.m_MemoryTracker.Init(&m_PreCommands, "PreCommand");
#endif
}

Frame::~Frame() {
}

//---------------------------------------------------------------------------------------

void Frame::Clear() {
	m_PreCommands.Clear();
}

void Frame::Submit() {
	m_PreCommands.Execute();

	Clear();
}

} //namespace Renderer 
} //namespace MoonGlare 

