/*
  * Generated by cppsrc.sh
  * On 2015-08-16 13:36:25,31
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#include <pch.h>
#include "Light_new.h"

namespace MoonGlare {
namespace Renderer {
namespace Light {

Light::Light() {
}

Light::~Light() {
}

} //namespace Light 
} //namespace Renderer 
} //namespace MoonGlare 
