/*
	Generated by cppsrc.sh
	On 2015-01-30 17:27:34,78
	by Paweu
*/

#pragma once
#ifndef ShadowMapShader_H
#define ShadowMapShader_H

namespace Graphic {
namespace Shaders {

struct ShadowMapShaderDescriptor {
	enum class InLayout {
		Position,
		TextureUV,
		Normal,
	};
	enum class OutLayout {
		FragColor,
	};
	enum class Uniform {
		CameraMatrix,
		ModelMatrix,
		BackColor,

	//	LightPosition,

		MaxValue,
	};

	constexpr static const char* GetName(Uniform u) {
		switch (u) {
		case Uniform::CameraMatrix: return "CameraMatrix";
		case Uniform::ModelMatrix: return "ModelMatrix";
		case Uniform::BackColor: return "Material.BackColor";
	//	case Uniform::LightPosition: return "LightPosition";
		default: return nullptr;
		}
	}
};

} //namespace Shaders 
} //namespace Graphic 

#endif

