#pragma once

#define ICON_RES16_PREFIX ":/icons/icons/"
#define ICON_RES16_POSTFIX ".png"

#define ICON_16_REFRESH_RESOURCE		ICON_RES16_PREFIX "blue_circle_left_arrows" ICON_RES16_POSTFIX
#define ICON_16_FOLDER_RESOURCE			ICON_RES16_PREFIX "yellow_folder" ICON_RES16_POSTFIX
#define ICON_16_ENTITYPATTERN_RESOURCE	ICON_RES16_PREFIX "blue_gear" ICON_RES16_POSTFIX
#define ICON_16_DELETE_RESOURCE			ICON_RES16_PREFIX "Erase" ICON_RES16_POSTFIX
#define ICON_16_CREATERESOURCE_RESOURCE ICON_RES16_PREFIX "green_create" ICON_RES16_POSTFIX
#define ICON_16_SCENEDESCR_RESOURCE		ICON_RES16_PREFIX "blue_sphere" ICON_RES16_POSTFIX
#define ICON_16_COPY_RESOURCE			ICON_RES16_PREFIX "Copy" ICON_RES16_POSTFIX
#define ICON_16_CUT_RESOURCE			ICON_RES16_PREFIX "Cut" ICON_RES16_POSTFIX
#define ICON_16_PASE_RESOURCE			ICON_RES16_PREFIX "Paste" ICON_RES16_POSTFIX
#define ICON_16_ARROW_UP_RESOURCE		ICON_RES16_PREFIX "blue_up_arrow" ICON_RES16_POSTFIX
#define ICON_16_ARROW_DOWN_RESOURCE		ICON_RES16_PREFIX "blue_down_arrow" ICON_RES16_POSTFIX
#define ICON_16_LUALOGO_RESOURCE		ICON_RES16_PREFIX "Lua-Logo_16x16" ICON_RES16_POSTFIX

#define ICON_16_REFRESH				QIcon(ICON_16_REFRESH_RESOURCE)
#define ICON_16_FOLDER				QIcon(ICON_16_FOLDER_RESOURCE)
#define ICON_16_LUALOGO				QIcon(ICON_16_LUALOGO_RESOURCE)
#define ICON_16_CREATE_RESOURCE		QIcon(ICON_16_CREATERESOURCE_RESOURCE)
#define ICON_16_DELETE				QIcon(ICON_16_DELETE_RESOURCE)
#define ICON_16_COPY				QIcon(ICON_16_COPY_RESOURCE)
#define ICON_16_CUT					QIcon(ICON_16_CUT_RESOURCE )
#define ICON_16_PASE				QIcon(ICON_16_PASE_RESOURCE)
#define ICON_16_ARROW_UP			QIcon(ICON_16_ARROW_UP_RESOURCE)
#define ICON_16_ARROW_DOWN			QIcon(ICON_16_ARROW_DOWN_RESOURCE)
