/*
  * Generated by cppsrc.sh
  * On 2015-02-26  1:07:52,02
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include <pch.h>
#include "InternalFileSystem.h"
#include "iFileWritter.h"
#include "iFileReader.h"

namespace MoonGlare {
namespace FileSystem {

GABI_IMPLEMENT_ABSTRACT_CLASS(iFileWritter)

iFileWritter::iFileWritter(iContainer *Owner):
		BaseClass(),
		m_Owner(Owner) {
}

iFileWritter::~iFileWritter() {
}

bool iFileWritter::SetFileData(FileReader reader) {
	return SetFileData(reader->GetFileData(), reader->Size());
}

bool iFileWritter::OwnData(std::unique_ptr<char[]> data, FileSize size) {
	return SetFileData(&data[0], size);
}

} //namespace FileSystem 
} //namespace MoonGlare 
