/*
	Generated by cppsrc.sh
	On 2015-01-24 10:42:43,61
	by Paweu
*/

#pragma once
#ifndef BassStream_H
#define BassStream_H

namespace MoonGlare {
namespace Modules {
namespace BassSound {

class BassStream : public iBassChannel {
	GABI_DECLARE_CLASS(BassStream, iBassChannel);
public:
 	BassStream();
 	virtual ~BassStream();
	virtual bool Initialize();
	virtual bool Finalize();
private: 
	StarVFS::ByteTable m_file;
};

} //namespace BassSound 
} //namespace Modules 
} //namespace MoonGlare 

#endif
