/*
  * Generated by cppsrc.sh
  * On 2016-01-10 15:31:17,47
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef ZlibCompression_H
#define ZlibCompression_H
#ifndef STARVFS_DISABLE_ZLIB

namespace StarVFS {
namespace Compression {

class Zlib {
public:
	Zlib();
	~Zlib();

	void SetCompressionlevel(Compressionlevel l) { m_Level = l; }

	int GetZLibLevel() const;

	CompressionResult Compress(const ByteTable &in, ByteTable &out);
	CompressionResult Decompress(const ByteTable &in, ByteTable &out);
private: 
	Compressionlevel m_Level;
};

} //namespace Compression 
} //namespace StarVFS 

#endif // STARVFS_DISABLE_ZLIB
#endif 
