/*
  * Generated by cppsrc.sh
  * On 2015-10-28 22:31:58,25
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef TaskManager_H
#define TaskManager_H

namespace MoonGlare {
namespace Renderer {
namespace Tasks {

/**

	Virtuality is forbidden in this class.
*/
class TaskManager final {
public:
 	TaskManager();
 	~TaskManager();

	bool Initialize();
	bool Finalize();

	/** execute all pending tasks */
	void Submmit();

	TextureRenderer& GetTextureRenderer() { return m_TextureRenderer; }
private: 
	TextureRenderer m_TextureRenderer;
};

} //namespace Tasks 
} //namespace Renderer 
} //namespace MoonGlare 

#endif
