/*
  * Generated by cppsrc.sh
  * On 2015-03-08 19:20:50,34
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once

namespace MoonGlare::DataClasses {

class StringTable {
public:
    StringTable(FileSystem::iFileSystem *fs);
    virtual ~StringTable();

    const string& GetString(const string& id, const string& Table);

    void Clear();
    //static void RegisterScriptApi(ApiInitializer &api);
protected:
    FileSystem::iFileSystem *fileSystem;
    struct StringTableInfo {
        StringStringMap StringMap;
        XMLFile XMLTableTranslation;
        XMLFile XMLTable;
    };

    using StringTableMap = std::unordered_map < string, StringTableInfo > ;
    StringTableMap m_TableMap;

    void InitInternalTable();

    bool Load(const string& TableName);
};

} //namespace MoonGlare::DataClasses
