/*
  * Generated by cppsrc.sh
  * On 2015-08-20 17:27:44,24
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef ComponentManager_H
#define ComponentManager_H

namespace MoonGlare {
namespace Core {
namespace Component {

class ComponentManager final {
public:
	ComponentManager();
	~ComponentManager();

	bool Initialize();
	bool Finalize();

	bool AddComponent(UniqueAbstractComponent uac);

	void Process(const MoveConfig &config);
private:
};

} //namespace Component 
} //namespace Core 
} //namespace MoonGlare 

#endif
