/*
  * Generated by cppsrc.sh
  * On 2015-08-20 17:27:44,24
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include <pch.h>
#include <nfMoonGlare.h>
#include <Foundation/Component/iSubsystem.h>
#include "SubsystemManager.h"
#include "ComponentRegister.h"
#include <Foundation/SoundSystem/Component/SoundSubsystem.h>

namespace MoonGlare {
namespace Core {
namespace Component {

//
struct SoundSubsystemWrap : SoundSystem::Component::SoundSubsystem, ComponentIDWrap<ComponentID::SoundSource> {
    template<typename ... ARGS>
    SoundSubsystemWrap(ARGS ... args) : SoundSubsystem(std::forward<ARGS>(args)...) { }
};

RegisterComponentID<SoundSubsystemWrap> SoundSubsystemIDReg("SoundSource", true, nullptr);
//&TransformComponent::RegisterScriptApi);

ComponentRegister::MapType *ComponentRegister::s_ComponentMap = nullptr;

void ComponentRegister::Dump(std::ostream &out) {
	out << "Component Register:\n";
	if (!s_ComponentMap) {
		out << "\tEmpty\n";
		return;
	}

	for (auto &it : *s_ComponentMap) {
		char buffer[128];
		sprintf_s(buffer, "\t%20s 0x%02x[%3d]\n", it.first.c_str(), (unsigned)it.second->m_CID, (unsigned)it.second->m_CID);
		out << buffer;
	}
}

bool ComponentRegister::ExtractCIDFromXML(pugi::xml_node node, ComponentID & out) {
	auto idxml = node.attribute("Id");
	if (idxml) {
		out = static_cast<ComponentID>(idxml.as_uint(0));
		return out != (ComponentID)ComponentID::Invalid;
	} else {
		auto namexml = node.attribute("Name");
		if (!namexml) {
			AddLogf(Error, "Component definition without id or name!");
			return false;
		}
		if (GetComponentID(namexml.as_string(""), out)) {
			return out != (ComponentID)ComponentID::Invalid;
		} else {
			AddLogf(Error, "Unknown component name: %s", namexml.as_string(""));
			return false;
		}
	}
	return false;
}

} //namespace Component 
} //namespace Core 
} //namespace MoonGlare 
