/*
  * Generated by cppsrc.sh
  * On 2015-08-20 17:27:44,24
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include <pch.h>
#include <nfMoonGlare.h>
#include "ComponentRegister.h"

namespace MoonGlare {
namespace Core {
namespace Component {

ComponentRegister::MapType *ComponentRegister::s_ComponentMap = nullptr;

void ComponentRegister::Dump(std::ostream &out) {
	out << "Component Register:\n";
	if (!s_ComponentMap) {
		out << "\tEmpty\n";
		return;
	}

	for (auto &it : *s_ComponentMap) {
		char buffer[128];
		sprintf_s(buffer, "\t%20s 0x%04X\n", it.first.c_str(), it.second);
		out << buffer;
	}
}

} //namespace Component 
} //namespace Core 
} //namespace MoonGlare 
