/*
	Generated by cppsrc.sh
	On 2015-01-30 17:27:34,78
	by Paweu
*/

#pragma once
#ifndef ShadowMapShader_H
#define ShadowMapShader_H

namespace Graphic {
namespace Shaders {

class ShadowMapShader : public Shader {
	GABI_DECLARE_CLASS_NOCREATOR(ShadowMapShader, Shader);
public:
 	ShadowMapShader(GLuint ShaderProgram, const string &ProgramName);
 	 ~ShadowMapShader();

	 void SetLightPosition(const math::vec3 &pos) {
		 glUniform3fv(m_LightPositionLocation, 1, &pos[0]);
	 }
protected:
	GLuint m_LightPositionLocation;
};

} //namespace Shaders 
} //namespace Graphic 

#endif

