/*
  * Generated by cppsrc.sh
  * On 2016-10-09 21:37:20,45
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once

#include <iFileProcessor.h>
#include <Module.h>

namespace MoonGlare {
namespace Editor {

class AsyncFileProcessor 
	: public QObject
    , public QtShared::iModule
    , public QtShared::iJobProcessor {
	Q_OBJECT;
public:
 	AsyncFileProcessor(QtShared::SharedModuleManager modmgr);
 	virtual ~AsyncFileProcessor();

    void Queue(QtShared::SharedFileProcessor processor)override;
    size_t GetQueuedJobCount() override;
signals:
	void FileProcessingFinished(QtShared::SharedFileProcessor);
protected:
    size_t jobcount = 0;
    bool m_ThreadCanWork;
	std::condition_variable m_QueueEmpty;
	std::list<QtShared::SharedFileProcessor> m_Queue;
	std::mutex m_Mutex;
	std::thread m_Thread;

	void ThreadEntry();
    void ExecuteJob(MoonGlare::QtShared::SharedFileProcessor processor);
protected slots:
	void JobFinished(QtShared::SharedFileProcessor);
};

} //namespace Editor 
} //namespace MoonGlare 
