/*
  * Generated by cppsrc.sh
  * On 2015-03-15  7:54:00.79
  * by Immethis
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef Encryption_H
#define Encryption_H
namespace MoonGlare {
namespace FileSystem {
namespace MoonGlareContainer {

} //namespace MoonGlareContainer 
} //namespace FileSystem 
} //namespace MoonGlare 

#endif
