/*
  * Generated by cppsrc.sh
  * On 2015-02-26  2:03:01,16
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#include <pch.h>
#include <nfMoonGlare.h>
#include "../InternalFileSystem.h"
#include "MoonGlareContainer.h"

namespace MoonGlare {
namespace FileSystem {
namespace MoonGlareContainer {

GABI_IMPLEMENT_CLASS_NOCREATOR(MoonGlareContainer)

MoonGlareContainer::MoonGlareContainer():
		BaseClass(),
		m_FileName() {
}

MoonGlareContainer::~MoonGlareContainer() {
}

bool MoonGlareContainer::Open(const string &FileName) {
	return false;
}

} //namespace MoonGlareContainer 
} //namespace FileSystem 
} //namespace MoonGlare 
