/*
  * Generated by cppsrc.sh
  * On 2015-08-20 17:27:44,24
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef ComponentOwner_H
#define ComponentOwner_H

namespace MoonGlare {
namespace Core {
namespace Component {

class AbstractComponent;

class ComponentOwner {
public:
 	ComponentOwner();
 	~ComponentOwner();
};

} //namespace Component 
} //namespace Core 
} //namespace MoonGlare 

#endif
