/*
  * Generated by cppsrc.sh
  * On 2016-07-21 20:17:41,09
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef DataModule_H
#define DataModule_H

#include <Project.x2c.h>
#include "../SaveableItem.h"

namespace MoonGlare {
namespace Editor {
namespace Module {

class DataModule 
	: public SaveableItemParent {
public:
	static std::shared_ptr<DataModule> NewModule(const std::string &MasterFile);
	static std::shared_ptr<DataModule> OpenModule(const std::string &MasterFile);
	DataModule(const std::string &MasterFile);
	virtual ~DataModule();

	std::string GetBaseDirectory();
protected:

	bool Create();
	bool Open();

	virtual bool DoPeriodicSave() override;
private:
	std::string m_MasterFile;
	x2c::Project::MoonGlareProject_t m_Project;
};

} //namespace Module 
} //namespace Editor 
} //namespace MoonGlare 

#endif
