/*
	Generated by cppsrc.sh
	On 2015-01-02 18:44:53,63
	by Paweu
*/
#include <pch.h>
#include "PhysicalProperties.h"
//#include <EngineHeader.h>

namespace Physics {

PhysicalProperties::PhysicalProperties() {
	Friction = 0.5f;
	Restitution = 0.3f;
	Damping.Angular = 0.2f;
	Damping.Linear = 0.2f;
}

bool PhysicalProperties::LoadMeta(const xml_node node) {
	bool success = true;

	success &= XML::ReadExistingChildAttribute(node, "Friction", "Value", Friction);
	success &= XML::ReadExistingChildAttribute(node, "Restitution", "Value", Restitution);
	success &= XML::ReadExistingChildAttribute(node, "Damping", "Linear", Damping.Linear);
	success &= XML::ReadExistingChildAttribute(node, "Damping", "Angular", Damping.Angular);

	return success;
}

} //namespace Physics 
