/*
  * Generated by cppsrc.sh
  * On 2015-03-01  6:55:05,01
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef Button_H
#define Button_H

namespace MoonGlare {
namespace GUI {
namespace Widgets {

class Button {
public:
 	Button();
 	virtual ~Button();
protected:
	//TODO: add stuff there
private: 
	//TODO: add stuff there
};

} //namespace Widgets 
} //namespace GUI 
} //namespace MoonGlare 

#endif

