/*
  * Generated by cppsrc.sh
  * On 2015-03-01  6:59:58,50
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include <pch.h>
#include "CheckBox.h"

namespace MoonGlare {
namespace GUI {
namespace Widgets {


CheckBox::CheckBox() {

}

CheckBox::~CheckBox() {

}

} //namespace Widgets 
} //namespace GUI 
} //namespace MoonGlare 
