/*
  * Generated by cppsrc.sh
  * On 2015-12-10 18:22:05,47
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once

namespace StarVFS {

struct Murmur3Hash32 {
	static FilePathHash Hash(const char *data, size_t len);
    static FilePathHash Hash(const std::string &str) { return Hash(str.c_str(), str.length()); }
};

using FilePathHashAlgorithm = Murmur3Hash32;

} //namespace StarVFS 
