/*
  * Generated by cppsrc.sh
  * On 2016-09-11 17:09:28,63
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef iEditor_H
#define iEditor_H

namespace MoonGlare {
namespace QtShared {

struct EditableFielInfo {
	std::string m_Ext;
	std::string m_Icon;
};

struct iEditorInfo {
	virtual ~iEditorInfo() {};
	virtual std::vector<EditableFielInfo> GetSupportedFileTypes() const = 0;
};

struct iEditor {
	virtual ~iEditor() { };
	virtual bool OpenData(const std::string &URI) { return false; }
	virtual bool SaveData() { return false; }
	virtual bool CloseData() { return false; }

	virtual bool Ischanged() { return true; }
	virtual bool CanDropChanges() { return false; }
	virtual bool DropChanges() { return false; }
protected:
};

} //namespace QtShared
} //namespace MoonGlare

#endif
