/*
  * Generated by cppsrc.sh
  * On 2016-09-11 17:09:28,63
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#include PCH_HEADER
#include "iEditor.h"

namespace MoonGlare {
namespace QtShared {

} //namespace QtShared
} //namespace MoonGlare
