/*
  * Generated by cppsrc.sh
  * On 2016-10-09 20:20:47,90
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef iFileIconProvider_H
#define iFileIconProvider_H

namespace MoonGlare {
namespace QtShared {

class iFileIconProvider {
public:
	virtual ~iFileIconProvider() { }

	struct FileIconInfo {
		std::string m_Ext;
		std::string m_Icon;
	};

	virtual std::vector<FileIconInfo> GetFileIconInfo() { return{}; }
};

using FileIconProviderClassRegister = Space::DynamicClassRegister<iFileIconProvider>;

} //namespace QtShared 
} //namespace MoonGlare 

#endif
