/*
  * Generated by cppsrc.sh
  * On 
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef LuaUtils_H
#define LuaUtils_H

namespace MoonGlare {
namespace Core {
namespace Scripts {

int LuaErrorHandler(lua_State *L);
int LuaTraceback(lua_State *L);
int LuaPanic(lua_State *L);

inline bool LuaSafeCall(lua_State *lua, int args, int rets, const char *CaleeName, int errf = 0) {
	try {
		AddLogf(ScriptCall, "Call to %s", CaleeName);
		return lua_pcall(lua, args, rets, errf) == 0;
	}
	catch (Core::Scripts::eLuaPanic &err) {
		AddLogf(Error, "Failure during call to %s message: %s", CaleeName, err.what());
		return false;
	}
}

template<typename T>
inline void LuaSetField(lua_State *lua, T t, const char *Name, int index) {
	Utils::Scripts::Lua_push(lua, t);
	lua_setfield(lua, index - 1, Name); // -1 -> to include pushed value
}

} //namespace Scripts 
} //namespace Core 
} //namespace MoonGlare 

#endif
