/*
	Generated by cppsrc.sh
	On 2015-01-22  6:51:10,16
	by Paweu
*/
#include <pch.h>
#include <MoonGlare.h>
#include <Engine/ModulesManager.h>
#include <Engine/iSoundEngine.h>
#include "NullSoundEngine.h"

namespace MoonGlare {
namespace Modules {
namespace NullSoundEngine {

struct NullSoundEngineModule : public MoonGlare::Modules::ModuleInfo {
	NullSoundEngineModule(): BaseClass("NullSoundEngine", ModuleType::Core) { }
	virtual bool Initialize() override {
		return (new NullSoundEngine())->Initialize();
	}
	virtual bool Finalize() override {
		if (NullSoundEngine::InstanceExists()) {
			GetSoundEngine()->Finalize();
			NullSoundEngine::DeleteInstance();
		}
		return true;
	}
};
DEFINE_MODULE(NullSoundEngineModule);

//----------------------------------------------------------------------------------

GABI_IMPLEMENT_STATIC_CLASS(NullSoundEngine);
RegisterApiDerivedClass(NullSoundEngine, &NullSoundEngine::RegisterScriptApi);

NullSoundEngine::NullSoundEngine():
		BaseClass() {
}

NullSoundEngine::~NullSoundEngine() { }

//----------------------------------------------------------------------------------

struct NullSoundEngineDebugApi {
#ifdef DEBUG_SCRIPTAPI
#endif
};

void NullSoundEngine::RegisterScriptApi(ApiInitializer &api) {
	api
	.deriveClass<ThisClass, BaseClass>("cNullSoundEngine")
	.endClass()
	;
}

//----------------------------------------------------------------------------------

bool NullSoundEngine::Initialize() { return true; }
bool NullSoundEngine::Finalize() { return true; }
iSound* NullSoundEngine::GetSound(const string & Name) { return nullptr; }
iSound* NullSoundEngine::GetMusic(const string & Name) { return nullptr; }

//----------------------------------------------------------------------------------

void NullSoundEngine::DumpContent(std::ostream & out) {}
void NullSoundEngine::ScanForSounds() { }
void NullSoundEngine::ConfigurationChanged(SettingsGroup what) { }
void NullSoundEngine::RegisterSound(string Name, string FileName) { }
void NullSoundEngine::RegisterMusic(string Name, string FileName) { }
void NullSoundEngine::PlaySound(const string &Name) { }
void NullSoundEngine::PlayMusic(const string &Name) { }
void NullSoundEngine::PlaySoundScript(const string &Name, const string &OnEndFunc, int param) { }
void NullSoundEngine::PlaySoundTimer(const string &Name, Object *sender, int tid) { }
void NullSoundEngine::PlayMusicScript(const string &Name, const string &OnEndFunc, int param) { }
void NullSoundEngine::PlayMusicTimer(const string &Name, Object *sender, int tid) { }
void NullSoundEngine::SetPlayList(const string& PlayListName) { }
void NullSoundEngine::StopMusic() { }
void NullSoundEngine::RunPlayList() { }
void NullSoundEngine::SoundNotifyEnd(iSound * s) { }
void NullSoundEngine::HandleSoundEndAction(SoundEndAction action, iSound *sound) { }
void NullSoundEngine::EnumerateAudio(EnumerationFunc func) { }

} //namespace NullSoundEngine 
} //namespace Modules 
} //namespace MoonGlare 
