/*
  * Generated by cppsrc.sh
  * On 2015-05-02 21:11:41,56
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef LoadingBaseScene_H
#define LoadingBaseScene_H

namespace Core {
namespace Scene {

class LoadingBaseScene : public ciScene {
	GABI_DECLARE_ABSTRACT_CLASS(LoadingBaseScene, ciScene)
public:
 	LoadingBaseScene();
 	virtual ~LoadingBaseScene();
	static void RegisterScriptApi(ApiInitializer &api);
protected:
};

} //namespace Scene 
} //namespace Core 

#endif
