find_program(LUA_EXECUTABLE lua REQUIRED)
execute_process(COMMAND ${LUA_EXECUTABLE} -v OUTPUT_VARIABLE LUA_EXECUTABLE_VERSION_STRING)
string(REGEX MATCH "(Lua [0-9]\\.[0-9]\\.[0-9])" LUA_EXECUTABLE_VERSION "${LUA_EXECUTABLE_VERSION_STRING}")
message("* Using lua interpretter ${LUA_EXECUTABLE} (${LUA_EXECUTABLE_VERSION}) during build")

set(BIN2C_TOOL ${LUA_EXECUTABLE} ${CMAKE_CURRENT_LIST_DIR}/../scripts/bin2c.lua)
