/*
  * Generated by cppsrc.sh
  * On 2017-02-10 15:35:25,52
  * by Kalessin
*/
/*--END OF HEADER BLOCK--*/

#include "nfRenderer.h"
#include "Frame.h"

namespace MoonGlare::Renderer {

bool Frame::Initialize(uint8_t BufferIndex, RenderDevice *device) {
	m_BufferIndex = BufferIndex;
	m_RenderDevice = device;

	m_Memory.GetStorage().MemZero();

	return true;
}

bool Frame::Finalize() {
	return true;
}

//----------------------------------------------------------------------------------

void Frame::BeginFrame() {

	m_QueuedTextureRender.ClearAllocation();
	m_Memory.Clear();
}

void Frame::EndFrame() {
}

//----------------------------------------------------------------------------------

} //namespace MoonGlare::Renderer 
