/*
  * Generated by cppsrc.sh
  * On 2017-02-09 21:34:50,23
  * by Kalessin
*/
/*--END OF HEADER BLOCK--*/
#pragma once

#include "Configuration.Renderer.h"
#include "FrameBuffer.h"

namespace MoonGlare::Renderer {

class RendererFacade final {
public:
	RendererFacade();
 	~RendererFacade();

    bool Initialize(const ContextCreationInfo& ctxifo);
    bool Finalize();

    /** Shall work on main thread; does not return until stopped */
    void Start();
    void Stop();
	
	void Step();

//	Context* CreateContext(const ContextCreationInfo& ctxifo);
	Context* CurrentContext() { return m_Context.get(); }
private:
    bool m_CanWork = false;

	std::unique_ptr<RenderDevice> m_Device;
	std::unique_ptr<Context> m_Context;
};

} //namespace MoonGlare::Renderer
