/*
	Generated by cppsrc.sh
	On 2015-01-14 22:23:34,81
	by Paweu
*/

#pragma once
#ifndef GeometryPassShader_H
#define GeometryPassShader_H

namespace Graphic {
namespace Dereferred {

};

} //namespace Dereferred
} //namespace Graphic 

#endif
