/*
  * Generated by cppsrc.sh
  * On 2015-07-16 22:48:40,19
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include <pch.h>
#include <MoonGlare.h>
#include <Engine/ModulesManager.h>
#include "MSVCDebug.h"
#include <Windows.h>

namespace MoonGlare {
namespace Debug {

struct MSVCDebuggerOutputPolicy {
	void write(const ::Log::LogLine *line, const char *c) {
		OutputDebugStringA(c);
	}
};

struct MSVCDebuggerFormatPolicy {
	void format(const ::Log::LogLine *line, char* buffer, size_t buffer_size) {
		const char* file = line->m_File;
		
		static const char *skipstr = "d:\\programowanie\\projekty\\!gry\\moonglare\\";
		static const int skip = strlen(skipstr);
		if (!memcmp(skipstr, line->m_File, skip))
			file += skip;

		sprintf_s(buffer, buffer_size, "%s(%d) : %s : %s\n", file, line->m_Line, line->m_ModeStr, line->m_Message);
	}
};

using MSVCDebuggerLogSink = ::Log::LogSink < MSVCDebuggerOutputPolicy, MSVCDebuggerFormatPolicy, ::Log::LogNoFilteringPolicy > ;

//----------------------------------------------------------------
 
struct MSVCDebugModule : public MoonGlare::Modules::ModuleInfo {
	MSVCDebugModule(): BaseClass("MSVCDebug", ModuleType::Debug) { }

	virtual bool Initialize() override {
		if (!IsDebuggerPresent())
			return false;
		new MSVCDebug();
		m_LoggerSink = std::make_unique<MSVCDebuggerLogSink>();
		m_LoggerSink->Enable();
		return true;
	}
	virtual bool Finalize() override {
		m_LoggerSink.reset();
		if (!MSVCDebug::InstanceExists())
			return true;
		MSVCDebug::DeleteInstance();
		return true;
	}
private:
	std::unique_ptr<MSVCDebuggerLogSink> m_LoggerSink;
};
DEFINE_MODULE(MSVCDebugModule);

//----------------------------------------------------------------

GABI_IMPLEMENT_CLASS_SINGLETON(MSVCDebug);
RegisterApiDerivedClass(MSVCDebug, &MSVCDebug::RegisterScriptApi);

MSVCDebug::MSVCDebug() {
	SetThisAsInstance();
}

MSVCDebug::~MSVCDebug() {
}

//----------------------------------------------------------------

void MSVCDebug::RegisterScriptApi(::ApiInitializer &root) {
	root
	.deriveClass<ThisClass, BaseClass>("cMSVCDebug")
	.endClass()
	;
}

//----------------------------------------------------------------

void MSVCDebug::DebuggerPrint(const char* line) {
	OutputDebugStringA(line);
}

void MSVCDebug::DebuggerPrint(const string& line) {
	OutputDebugStringA(line.c_str());
}

} //namespace Debug 
} //namespace MoonGlare 
